
# This file is automatically generated during the generation of setup.py
# Copyright 2020-2021, Caer
author = "Jason Dsouza"
author_email = "jasmcaus@gmail.com"
version = "2.0.8"
full_version = "2.0.8"
git_version = '11ff37867c2cb86a92aceb0ac24accb3607e3635'
release = True
contributors = ['Jason Dsouza <@jasmcaus>', '', 'Special Thanks to:', '@MalikMAlna', '@lucasace', '@GitHubDragonFly', '@brccabral', '@theSekyi']
homepage = "https://github.com/jasmcaus/caer"
