
# This file is automatically generated during the generation of setup.py
# Copyright 2020-2021, Caer
author = "Jason Dsouza"
author_email = "jasmcaus@gmail.com"
version = "2.0.8"
full_version = "2.0.8"
git_version = '06733ea60f9b6ab4035fa9fc3f8927b89e8b0e68'
release = True
contributors = ['Jason Dsouza <@jasmcaus>', '', 'Special Thanks to:', '@MalikMAlna', '@lucasace', '@GitHubDragonFly', '@brccabral', '@theSekyi']
homepage = "https://github.com/jasmcaus/caer"
